# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'generador_numerosDZIRxk.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 621)
        MainWindow.setStyleSheet(u"background-color:rgb(223, 206, 234);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.txt_semilla = QLineEdit(self.centralwidget)
        self.txt_semilla.setObjectName(u"txt_semilla")
        self.txt_semilla.setGeometry(QRect(80, 160, 113, 20))
        self.txt_semilla.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"")
        self.lb_semilla = QLabel(self.centralwidget)
        self.lb_semilla.setObjectName(u"lb_semilla")
        self.lb_semilla.setGeometry(QRect(10, 160, 47, 13))
        font = QFont()
        font.setPointSize(10)
        self.lb_semilla.setFont(font)
        self.btnGenerar = QPushButton(self.centralwidget)
        self.btnGenerar.setObjectName(u"btnGenerar")
        self.btnGenerar.setGeometry(QRect(490, 500, 101, 41))
        self.btnGenerar.setStyleSheet(u"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(108, 138, 229, 255), stop:0.477273 rgba(161, 235, 219, 255), stop:1 rgba(4, 218, 182, 255))")
        self.cb_cuadrados = QCheckBox(self.centralwidget)
        self.cb_cuadrados.setObjectName(u"cb_cuadrados")
        self.cb_cuadrados.setGeometry(QRect(30, 50, 91, 17))
        self.cb_cuadrados.setFont(font)
        self.cb_congruencias = QCheckBox(self.centralwidget)
        self.cb_congruencias.setObjectName(u"cb_congruencias")
        self.cb_congruencias.setGeometry(QRect(30, 70, 101, 17))
        self.cb_congruencias.setFont(font)
        self.cb_normal = QCheckBox(self.centralwidget)
        self.cb_normal.setObjectName(u"cb_normal")
        self.cb_normal.setGeometry(QRect(30, 90, 101, 17))
        self.cb_normal.setFont(font)
        self.lb_generacion = QLabel(self.centralwidget)
        self.lb_generacion.setObjectName(u"lb_generacion")
        self.lb_generacion.setGeometry(QRect(10, 20, 171, 21))
        font1 = QFont()
        font1.setFamily(u"Times New Roman")
        font1.setPointSize(14)
        self.lb_generacion.setFont(font1)
        self.lb_semilla_2 = QLabel(self.centralwidget)
        self.lb_semilla_2.setObjectName(u"lb_semilla_2")
        self.lb_semilla_2.setGeometry(QRect(10, 200, 47, 13))
        self.lb_semilla_2.setFont(font)
        self.txt_min = QLineEdit(self.centralwidget)
        self.txt_min.setObjectName(u"txt_min")
        self.txt_min.setGeometry(QRect(80, 200, 113, 20))
        self.txt_min.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.txt_max = QLineEdit(self.centralwidget)
        self.txt_max.setObjectName(u"txt_max")
        self.txt_max.setGeometry(QRect(80, 240, 113, 20))
        self.txt_max.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_semilla_3 = QLabel(self.centralwidget)
        self.lb_semilla_3.setObjectName(u"lb_semilla_3")
        self.lb_semilla_3.setGeometry(QRect(10, 240, 47, 13))
        self.lb_semilla_3.setFont(font)
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(280, 50, 511, 431))
        self.scrollArea.setStyleSheet(u"background-color:qradialgradient(spread:reflect, cx:0.5, cy:0.5, radius:0.5, fx:0.682, fy:0.319, stop:0.380682 rgba(133, 77, 151, 255), stop:1 rgba(119, 153, 255, 255))")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 509, 429))
        self.datos = QTableView(self.scrollAreaWidgetContents)
        self.datos.setObjectName(u"datos")
        self.datos.setGeometry(QRect(10, 10, 491, 411))
        self.datos.setStyleSheet(u"background-color:rgb(201, 176, 255);")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lb_c = QLabel(self.centralwidget)
        self.lb_c.setObjectName(u"lb_c")
        self.lb_c.setGeometry(QRect(10, 380, 47, 13))
        self.lb_c.setFont(font)
        self.txt_c = QLineEdit(self.centralwidget)
        self.txt_c.setObjectName(u"txt_c")
        self.txt_c.setGeometry(QRect(80, 380, 113, 20))
        self.txt_c.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.txt_k = QLineEdit(self.centralwidget)
        self.txt_k.setObjectName(u"txt_k")
        self.txt_k.setGeometry(QRect(80, 340, 113, 20))
        self.txt_k.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_k = QLabel(self.centralwidget)
        self.lb_k.setObjectName(u"lb_k")
        self.lb_k.setGeometry(QRect(10, 340, 47, 13))
        self.lb_k.setFont(font)
        self.lb_g = QLabel(self.centralwidget)
        self.lb_g.setObjectName(u"lb_g")
        self.lb_g.setGeometry(QRect(10, 420, 47, 16))
        self.lb_g.setFont(font)
        self.txt_g = QLineEdit(self.centralwidget)
        self.txt_g.setObjectName(u"txt_g")
        self.txt_g.setGeometry(QRect(80, 420, 113, 20))
        self.txt_g.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_m = QLabel(self.centralwidget)
        self.lb_m.setObjectName(u"lb_m")
        self.lb_m.setGeometry(QRect(10, 530, 47, 13))
        self.lb_m.setFont(font)
        self.txt_m = QLineEdit(self.centralwidget)
        self.txt_m.setObjectName(u"txt_m")
        self.txt_m.setGeometry(QRect(70, 530, 113, 20))
        self.txt_m.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_m_2 = QLabel(self.centralwidget)
        self.lb_m_2.setObjectName(u"lb_m_2")
        self.lb_m_2.setGeometry(QRect(10, 500, 261, 16))
        self.lb_m_2.setFont(font)
        self.cb_paridad = QCheckBox(self.centralwidget)
        self.cb_paridad.setObjectName(u"cb_paridad")
        self.cb_paridad.setGeometry(QRect(10, 460, 231, 17))
        self.cb_paridad.setFont(font)
        self.lb_m_3 = QLabel(self.centralwidget)
        self.lb_m_3.setObjectName(u"lb_m_3")
        self.lb_m_3.setGeometry(QRect(10, 560, 47, 13))
        self.lb_m_3.setFont(font)
        self.txt_a = QLineEdit(self.centralwidget)
        self.txt_a.setObjectName(u"txt_a")
        self.txt_a.setGeometry(QRect(70, 560, 113, 20))
        self.txt_a.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btnSubir = QPushButton(self.centralwidget)
        self.btnSubir.setObjectName(u"btnSubir")
        self.btnSubir.setGeometry(QRect(200, 540, 111, 31))
        self.btnSubir.setStyleSheet(u"background-color:rgb(165, 169, 255)")
        self.lb_archivo = QLabel(self.centralwidget)
        self.lb_archivo.setObjectName(u"lb_archivo")
        self.lb_archivo.setGeometry(QRect(320, 550, 151, 21))
        self.lb_archivo.setFont(font)
        self.lb_generacion_2 = QLabel(self.centralwidget)
        self.lb_generacion_2.setObjectName(u"lb_generacion_2")
        self.lb_generacion_2.setGeometry(QRect(240, 0, 561, 21))
        self.lb_generacion_2.setFont(font1)
        self.btnDescargar = QPushButton(self.centralwidget)
        self.btnDescargar.setObjectName(u"btnDescargar")
        self.btnDescargar.setGeometry(QRect(670, 490, 111, 31))
        self.btnDescargar.setStyleSheet(u"background-color:rgb(165, 169, 255)")
        MainWindow.setCentralWidget(self.centralwidget)
        self.scrollArea.raise_()
        self.txt_semilla.raise_()
        self.lb_semilla.raise_()
        self.btnGenerar.raise_()
        self.cb_cuadrados.raise_()
        self.cb_congruencias.raise_()
        self.cb_normal.raise_()
        self.lb_generacion.raise_()
        self.lb_semilla_2.raise_()
        self.txt_min.raise_()
        self.txt_max.raise_()
        self.lb_semilla_3.raise_()
        self.lb_c.raise_()
        self.txt_c.raise_()
        self.txt_k.raise_()
        self.lb_k.raise_()
        self.lb_g.raise_()
        self.txt_g.raise_()
        self.lb_m.raise_()
        self.txt_m.raise_()
        self.lb_m_2.raise_()
        self.cb_paridad.raise_()
        self.lb_m_3.raise_()
        self.txt_a.raise_()
        self.btnSubir.raise_()
        self.lb_archivo.raise_()
        self.lb_generacion_2.raise_()
        self.btnDescargar.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        self.menuGenerar = QMenu(self.menubar)
        self.menuGenerar.setObjectName(u"menuGenerar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuGenerar.menuAction())

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Generador", None))
        self.lb_semilla.setText(QCoreApplication.translate("MainWindow", u"Semilla", None))
        self.btnGenerar.setText(QCoreApplication.translate("MainWindow", u"Generar Numeros", None))
        self.cb_cuadrados.setText(QCoreApplication.translate("MainWindow", u"Cuadrados", None))
        self.cb_congruencias.setText(QCoreApplication.translate("MainWindow", u"Congruencias", None))
        self.cb_normal.setText(QCoreApplication.translate("MainWindow", u"Dist. Normal", None))
        self.lb_generacion.setText(QCoreApplication.translate("MainWindow", u"Tipo de generacion", None))
        self.lb_semilla_2.setText(QCoreApplication.translate("MainWindow", u"min", None))
        self.txt_max.setText("")
        self.lb_semilla_3.setText(QCoreApplication.translate("MainWindow", u"max", None))
        self.lb_c.setText(QCoreApplication.translate("MainWindow", u"c", None))
        self.lb_k.setText(QCoreApplication.translate("MainWindow", u"k", None))
        self.lb_g.setText(QCoreApplication.translate("MainWindow", u"g", None))
        self.txt_g.setText("")
        self.lb_m.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.txt_m.setText("")
        self.lb_m_2.setText(QCoreApplication.translate("MainWindow", u"Numero de aleatorios especificos (avanzado)", None))
        self.cb_paridad.setText(QCoreApplication.translate("MainWindow", u"Paridad Par (marcar si es Par)", None))
        self.lb_m_3.setText(QCoreApplication.translate("MainWindow", u"a", None))
        self.txt_a.setText("")
        self.btnSubir.setText(QCoreApplication.translate("MainWindow", u"Subir Experimentales", None))
        self.lb_archivo.setText(QCoreApplication.translate("MainWindow", u"archivo", None))
        self.lb_generacion_2.setText(QCoreApplication.translate("MainWindow", u"Info: ", None))
        self.btnDescargar.setText(QCoreApplication.translate("MainWindow", u"Descargar datos", None))
        self.menuGenerar.setTitle(QCoreApplication.translate("MainWindow", u"Generar", None))
    # retranslateUi

